name: Deploy manually

on:
  workflow_dispatch:
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Deploy to strato via sftp'

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
    
    - name: List ftp
      run: echo ${SFTP_PASS} > sftp ${SFTP_HOST} && ls
