name: Deploy to webspace

on:
  push:
   branches: master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Setup sshpass
      run: sudo apt update && sudo apt install sshpass
    - run: sshpass -V
    
    - name: Add known host
      env:
        SSHPASS: ${{ secrets.SFTP_PASS }}
        SFTP_HOST: ${{ secrets.SFTP_HOST }}
        SSH_SERVER: ${{ secrets.SSH_SERVER }}
      run: mkdir ~/.ssh && sshpass -e ssh-keyscan -H "$SSH_SERVER" >> ~/.ssh/known_hosts
    
    - name: test
      run: ls ./
      
    - name: test2
      run: ls /
    
    - name: List ftp
      env:
        SFTP_HOST: ${{ secrets.SFTP_HOST }}
        SSHPASS: ${{ secrets.SFTP_PASS }}
      run: sshpass -e sftp "$SFTP_HOST" <<< $"put -r ./ ./Personal-Site"
