name: Deploy manually

on:
  push:
   branches: master
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
    
    - name: Setup sshpass
      run: sudo apt update && sudo apt install sshpass
    - run: sshpass -V
    
    - name: List ftp
      env:
        SFTP_HOST: ${{ secrets.SFTP_HOST }}
        SSHPASS: ${{ secrets.SFTP_PASS }}
      run: sshpass -e sftp "$SFTP_HOST" << ! \
           ls \
           !
