name: Deploy to webspace

on:
  push:
   branches: master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Setup sshpass
      run: sudo apt update && sudo apt install sshpass
    - run: sshpass -V
    
    - name: List ftp
      env:
        SFTP_HOST: ${{ secrets.SFTP_HOST }}
        SSHPASS: ${{ secrets.SFTP_PASS }}
      run: |
        sshpass -e sftp "$SFTP_HOST" << !\
        ls\
        !
